### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by dandv** [naugtur/insertionQuery#16]
[Some users don't have a need for bower, and just use npm](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool).

**Comment by naugtur** [comment]
Sure, I actually never used bower myself, and am a heavy user of npm. I just made this lib before npm was the obvious choice ;)

**Comment by dandv** [comment]
> c:\prg\idr\website\tests>npm install insertion-query 
> insertion-query@1.0.2 ..\node_modules\insertion-query

Thanks!

**Comment by naugtur** [comment]
1.0.2 was broken, make sure you have latest.
