### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by dandv** [naugtur/insertionQuery#18]
* README to mention `npm install insertion-query`
* gh-pages branch is behind master. Maybe use just gh-pages? See http://stackoverflow.com/questions/15285324/is-there-a-way-to-use-a-pre-post-commit-hook-in-github-to-update-gh-pages-branch/30646245#30646245
* Set the URL of this GitHub repo to something, maybe the gh-pages page or https://www.npmjs.com/package/insertion-query

**Comment by naugtur** [comment]
readme is already there, 
gh-pages was good for testing, but jasmine urls are deprecated. switching to zuul+saucelabs might work
