### ISSUE TITLE
Target iframe DOM

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [naugtur/insertionQuery#29]
Can we use this excellent approach to target an iframe DOM also?

Actually we need to target a DOM element inside an iframe that is inside an iframe ;-(

Please advise.

Kind regards,
Mario

**Comment by naugtur** [comment]
Look into **seamless** iframes maybe, if you're in the same origin as all iframe ocntents, but generally, I don't think it'd be possible.
You should run this in the iframe at the bottom and use postmessage to communicate up.
