### ISSUE TITLE
crash on null element

### ISSUE THREAD

**Issue by yonatanLehman** [naugtur/insertionQuery#32]
I'm using insertQ to disable intercom when doing a visual test of my site.
```
  if (intercomState == "false") {
	insertionQ('#intercom-container').every(function(element){
	   document.getElementById("intercom-container").style.display = "none";
	})
  }
```

This crashes as follows:
![image](https://user-images.githubusercontent.com/32838532/64535508-1d918100-d320-11e9-9bbe-038eaca3e4b9.png)

I patched/fixed it by testing for null/undefined as the first line of tagAll and it solved the problem

    function tagAll(e) {
        if (!e) return;

BTW1 - the intercome icon still shows up briefly - is there a way to make it invisible before it appears?
BTW2 - I assume I could have written 
`element.style.display = "none" - correct ?`

Thanks for this feature - it saved me..

**Comment by naugtur** [comment]
Would you like to turn this into a pull request? If it's a single line, it should be doable through github UI. Would be nice to see you in the contributor list for that.

And yes, `element` is the element on which the event fired, so it has to match your initial selector.

**Comment by yonatanLehman** [comment]
Will do.



בתאריך יום ג׳, 10 בספט׳ 2019, 22:44, מאת Zbyszek Tenerowicz ‏<
notifications@github.com>:
