### ISSUE TITLE
Is it possible to detect when a matching node is removed?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [naugtur/insertionQuery#35]
Hello @naugtur !

Your plugin works great for detecting when new node elements are added and is very easy to use!

Is it possible for it to detect when the elements are removed as well?

I'm working with a drag-and-drop file upload plugin and I need to detect when a file is added or removed from the parent element. 

Thanks for any help or insights!

All the best,
Blake

**Comment by naugtur** [comment]
this is a workaround for wider browser support. but all modern browsers already have mutation observers. you should use them instead.
they're a bit harder to use but way better than this

**Comment by Blake-LeBlanc** [comment]
Thank you Zbyszek!
